### ISSUE TITLE
Cannot compile Java 7 projects with installed Elixir plugin

### ISSUE THREAD

**Issue by cedriessen** [KronicDeth/intellij-elixir#290]
Java 7 projects do not compile anymore when the Elixir plugin is installed. The following error occurs. 

I am wondering if this issue relates to https://github.com/ignatov/intellij-erlang/issues/727

> Error:Internal error: (java.lang.UnsupportedClassVersionError) com/intellij/execution/ExecutionException : Unsupported major.minor version 52.0
java.lang.UnsupportedClassVersionError: com/intellij/execution/ExecutionException : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.elixir_lang.jps.builder.ElixirBuilderService.createBuilders(ElixirBuilderService.java:25)
	at org.jetbrains.jps.incremental.BuilderRegistry.<init>(BuilderRegistry.java:53)
	at org.jetbrains.jps.incremental.BuilderRegistry.<init>(BuilderRegistry.java:33)
	at org.jetbrains.jps.incremental.BuilderRegistry$Holder.<clinit>(BuilderRegistry.java:36)
	at org.jetbrains.jps.incremental.BuilderRegistry.getInstance(BuilderRegistry.java:43)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:132)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:294)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:232)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zyuyou** [comment]
It seems to be that. So, wait for it.

**Comment by KronicDeth** [comment]
Based on #295 and #293, 3.0.1 might be built against too new of a version of IntelliJ, so this might not or might not be the same as ignatov/intellij-erlang#727.  That or #295 and #293 are actually related to ignatov/intellij-erlang#727.

**Comment by KronicDeth** [comment]
I can get a build loop that works in IntelliJ 1.4 and JDK 1.6

1. Build IntelliJ Elixir in IntelliJ 14.1 using JDK 1.6 with the project SDK set to IntelliJ 14.1 using JDK 1.6 (call this `intellij-elixir-14.1-1.6-14.1-1.6.zip`)
2. Installl `intellij-elixir-14.1-1.6-14.1-1.6.zip` into IntelliJ 14.1.
3. Rebuild `intellij-elixir-14.1-1.6-14.1-1.6.zip` in IntelliJ 14.1
4. Build works

The same build process breaks in IntelliJ 2016.1
1. Install `intellij-elixir-14.1-1.6-14.1-1.6.zip` into IntelliJ 2016.1
2. Build IntelliJ Elixir in IntelliJ 2016.1 using JDK 1.8 with the project SDK set to IntelliJ 14.1 using JDK 1.6
```
Error:Internal error: (java.lang.NoClassDefFoundError) Could not initialize class org.jetbrains.jps.incremental.BuilderRegistry$Holder
java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.jps.incremental.BuilderRegistry$Holder
	at org.jetbrains.jps.incremental.BuilderRegistry.getInstance(BuilderRegistry.java:43)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:132)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:294)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:232)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
```

Try building with project SDK set to IntelliJ 2016.1 with JDK 1.8
1. Build IntelliJ Elixir in IntelliJ 2016.1 using JDK 1.8 with the project SDK set to IntelliJ 14.1 using JDK 1.6 (call this `intellij-elixir-2016.1-1.8-2016.1-1.8.zip`)
2. Install `intellij-elixir-2016.1-1.8-2016.1-1.8.zip` into IntelliJ 2016.1
3. Build IntelliJ Elixir in IntelliJ 2016.1 using JDK 1.8 with the project SDK set to IntelliJ 14.1 using JDK 1.6
4. Build works

**Comment by KronicDeth** [comment]
Related to https://github.com/KronicDeth/intellij-elixir/issues/290#issuecomment-222693633: it looks like org/jetbrains/jps/incremental/BuilderRegistry$Holder.class changed jars between versions:

14.1: jps-server.jar
2016.1: jps-builders.jar

**Comment by KronicDeth** [comment]
Sorry to pull you out of https://github.com/ignatov/intellij-erlang/issues/727, @chashnikov.  This is the equivalent issue for intellij-elixir.  Is there a way to make https://github.com/KronicDeth/intellij-elixir/issues/290#issuecomment-222693633 work?  I've been targeting IntelliJ 14.1 through 2016.1 for intellij-elixir, but building in IntelliJ 14.1 using JDK 1.6 leads to `org.jetbrains.jps.incremental.BuilderRegistry$Holder` not being found when run in IntelliJ 2016.1 using JDK 1.8.  Do I need to do a dynamic classpath since the jars changed (see https://github.com/KronicDeth/intellij-elixir/issues/290#issuecomment-225342026)?
